package ru.kvartalovea.catscafe.common.ui.theme

import androidx.compose.ui.graphics.Color

internal val OrangePrimary = Color(0xFFF08200)
internal val OrangeOnPrimary = Color(0xFFFFFFFF)
internal val OrangeContainer = Color(0xFFFFE2C2)
internal val OnOrangeContainer = Color(0xFF3A1E00)
internal val OrangeDark = Color(0xFFFF9D2E)
internal val OrangeContainerDark = Color(0xFF5A3500)
internal val OnOrangeContainerDark = Color(0xFFFFE2C2)
internal val NavyPrimary = Color(0xFF142339)
internal val OnNavy = Color(0xFFFFFFFF)
internal val NavyContainer = Color(0xFFD8E0F0)
internal val OnNavyContainer = Color(0xFF0A1424)
internal val NavyDark = Color(0xFF8FA6CC)
internal val NavyContainerDark = Color(0xFF1F3258)
internal val OnNavyContainerDark = Color(0xFFD8E0F0)
internal val GreenAccent = Color(0xFF2EA055)
internal val OnGreenAccent = Color(0xFFFFFFFF)
internal val GreenContainer = Color(0xFFC9EBD4)
internal val OnGreenContainer = Color(0xFF0E3A1E)
internal val GreenAccentDark = Color(0xFF6FCB8B)
internal val GreenContainerDark = Color(0xFF154A2A)
internal val OnGreenContainerDark = Color(0xFFC9EBD4)

// Ошибки — Material defaults
internal val ErrorRed = Color(0xFFB3261E)
internal val OnErrorRed = Color(0xFFFFFFFF)
internal val ErrorRedContainer = Color(0xFFF9DEDC)
internal val OnErrorRedContainer = Color(0xFF410E0B)
internal val ErrorRedDark = Color(0xFFF2B8B5)
internal val ErrorRedContainerDark = Color(0xFF601410)
internal val OnErrorRedContainerDark = Color(0xFFF9DEDC)

// Нейтрали (фоны/текст)
internal val NeutralBackgroundLight = Color(0xFFFFFFFF)
internal val NeutralSurfaceLight = Color(0xFFFFFFFF)
internal val NeutralSurfaceVariantLight = Color(0xFFF4F5F7)
internal val NeutralOnSurfaceLight = Color(0xFF14171F)
internal val NeutralOnSurfaceVariantLight = Color(0xFF5B6473)
internal val NeutralOutlineLight = Color(0xFFE5E7EB)
internal val NeutralOutlineVariantLight = Color(0xFFEFF1F4)

internal val NeutralBackgroundDark = Color(0xFF101218)
internal val NeutralSurfaceDark = Color(0xFF181B22)
internal val NeutralSurfaceVariantDark = Color(0xFF22262F)
internal val NeutralOnSurfaceDark = Color(0xFFECEDF1)
internal val NeutralOnSurfaceVariantDark = Color(0xFFA8AEBA)
internal val NeutralOutlineDark = Color(0xFF323742)
internal val NeutralOutlineVariantDark = Color(0xFF272B33)
